name: Publish Python üêç distributions üì¶ to PyPI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10.4
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.4

    - name: Gets the tag version
      id: context
      run: |
        echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/}

    - name: Setup the Python Environment by installing Poetry
      uses: ./.github/actions/setup-python-build-env

    - name: Poetry check version, build and publish
      shell: bash
      run: |
        proj_version=$(poetry version -s)
        if [ $proj_version != $TAG_VERSION ]; then echo "Version $proj_version, defined in pyproject.toml, does not match TAG $TAG_VERSION of this release"; exit 3; fi
        poetry update
        poetry publish --build --username $PYPI_USER --password $PYPI_PASS
      env:
        TAG_VERSION: ${{ steps.context.outputs.TAG_VERSION }}
        PYPI_USER: ${{ secrets.PUBLIC_PYPI_USER }}
        PYPI_PASS: ${{ secrets.PUBLIC_PYPI_PASS }}
