name: PR Python üêç to Switch Repo

on:
  pull_request:
    branches:
      - master

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0

    - name: Setup the Python Environment by installing Poetry
      uses: ./.github/actions/setup-python-build-env

    - name: Create env file
      run: |
        cp .env.dev.local .env

# TODO: Fix MyPy issues https://github.com/SwitchEV/iso15118/issues/93
#    - name: Mypy
#      run: make mypy

    - name: Black
      run: make black

    - name: Flake8
      run: make flake8

    - name: isort
      run: make isort

    - name: Tests
      run: make test
